# Generated by Django 4.2.2 on 2023-06-07 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
